contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nfmop channel"
    url: https://nfcore.slack.com/channels/nfmop
    about: Discussion about the nf-core/nfmop pipeline
